### PR TITLE
make mistakes a requireable module, use browservefy for local dev

### PR DESCRIPTION
**Pull request by max-mapper**
this has a number of changes:
- fixes a discrepancy where your package.json specified the nonexistant `index.js` as the main: moved contents of site.js into index.js
- changes example page to only require a single compiled bundle instead of multiple bundles
- wraps the JS syntax for codemirror in a module.exports function so it can be require()'d
- moved inline script tag code from demo page into site.js
- implements `npm start` using `browservefy`, which builds the bundle each time you refresh the page
- installs local copies of browserify and browservefy to make setup easier (people wont need to have globally installed them)

I think thats it

### CODE REVIEW

**Comment by tmcw** [comment]
Awesome! This currently breaks the non-browservify version (what's served off of gh-pages). I think all that's needed is a hit to the Makefile:

```
js/bundle.js: js/site.js package.json
    browserify js/site.js > js/bundle.js
```

Instead of the `browserify -r` chunk that's there right now.

**Comment by max-mapper** [comment]
ah good point, do you wanna do it or should I?

**Comment by tmcw** [comment]
Probably cleanest if you do, otherwise it's a bit of git tango.

**Comment by max-mapper** [comment]
okey dokey should be all set

**Comment by tmcw** [comment]
Sweet! Merged, thx.

**Pull request merged**
