### PR TITLE
Evaluate within function scopes!

### PR DESCRIPTION
**Pull request by kirbysayshi**
I wanted to have content within functions be evaluated if possible too.
This is mostly a start, and it could be taken further.

With this code, the following will work:

```
var a = function(){
    var f = 'what';     // undefined
    f + 'who';          // "whatwho"
}
```

Function params throw a wrench, because the variables are never "reset".
For example:

```
var a = function(f){
    f += 'what';        // "whatwhatwhatwhat"
    f + 'who';          // "whatwhatwhatwhatwho"
}
```

The repeat happens every time the area is reevaluated. I thought about
scanning for args in the function, and then prepending 'f="default"' to
the eval'ed string. But it's impossible to know what to initialize them
with.

Thoughts?

### CODE REVIEW

**Comment by tmcw** [comment]
True, this would be quite neat! I'm not totally sure of what it looks like though - right now mistakes is 'honest' as in the values it displays are values-at-execution - if we were to let it say values within functions which can be called more than once, I guess it should be value-at-last-execution? A little wary of imbuing this part with too much magic.

**Comment by kirbysayshi** [comment]
I agree about the magic part, and this was definitely an experiment to see if it was even possible. There might be an "honest" way to enable something close to this, but I guess it requires more thought. I love the simplicity of mistakes, and of course don't want to wreck that.

**Comment by afeld** [comment]
I wonder how [Light Table](http://www.lighttable.com/) handles this... might be a good thing to draw inspiration from.

**Comment by tmcw** [comment]
Afaik, the JS support in Light Table isn't available yet. We'll have to see how they fare in languages less idyllic than lisps :)

**Comment by afeld** [comment]
Right right - I just meant the UX for showing variable values within functions that may be called multiple times.

**Comment by kirbysayshi** [comment]
That's actually a great point. I tried getting LightTable up and running a
few weeks ago, but know nothing of Clojure... it prompted me with "connect
to project" and I said, "I just want to try it out!"

Do either of you have experience with LT?

Yip yip,
~ Drew*

**Comment by afeld** [comment]
Negatory - neither.  I've just seen demos.

**Comment by tmcw** [comment]
Inner-function instrumentation is now done in rpl, and mistakes.io will eventually have its core replaced by that.

**Pull request closed without merging**
